@startuml
package api {
    class PaymentCalculationApi {
        + PaymentCalculationResponse calculate(PaymentCalculationRequest request)
    }
    class PaymentCalculationRequest {
    }
    class PaymentCalculationResponse {
    }
}
package service {
    class PaymentCalculationService {
        + 割り勘計算後金額 calculate(飲み会全体の人数, 請求金額)
    }
}
package domain {
    class 飲み会全体の人数 {
        - 多めの人数
        - 普通の人数
        - 少なめの人数
    }
    class 多めの人数 {
        - int
    }

    class 普通の人数 {
        - int
     }

    class 少なめの人数 {
        - int
     }

    class 請求金額 {
        - int
    }

    class 支払金額 {
        - 多めの人の支払金額
        - 普通の人の支払金額
        - 少なめの人の支払金額
    }

    class 多めの人の支払金額 {
        - int
    }

    class 普通の人の支払金額 {
        - int
    }

    class 少なめの人の支払金額 {
        - int
    }

    class 不足金額 {
        - int
    }

    class 割り勘計算後金額 {
        - 支払金額
        - 不足金額
    }


    class 割り勘計算 {
        + 割り勘計算後金額 計算する(飲み会全体の人数, 請求金額)
    }

    class 多めの人が支払う金額計算 {
        + 多めの人が支払う金額計算結果 計算する(飲み会全体の人数, 請求金額)
    }

    class 普通の人が支払う金額計算 {
        + 普通の人が支払う金額計算結果 計算する(飲み会全体の人数, 請求金額, 多めの人が支払う金額計算結果)
    }

    class 少なめの人が支払う金額計算 {
        + 少なめの人が支払う金額計算結果 計算する(飲み会全体の人数, 請求金額, 普通の人が支払う金額計算結果)
    }

    class 多めの人が支払う金額計算結果 {
        - 多めの人の支払金額
        - 請求額の残額
    }

    class 普通の人が支払う金額計算結果 {
        - 普通の人の支払金額
        - 請求額の残額
    }

    class 少なめの人が支払う金額計算結果 {
        - 少なめの人の支払金額
        - 不足金額
    }

    class 請求額の残額 {
        - int
    }

    class 支払金額計算 {
        + 割り勘計算後金額 計算する(多めの人が支払う金額計算結果, 普通の人が支払う金額計算結果, 少なめの人が支払う金額計算結果)
    }

}
PaymentCalculationApi --> PaymentCalculationRequest
PaymentCalculationApi --> PaymentCalculationResponse
PaymentCalculationApi --> PaymentCalculationService
PaymentCalculationService --> 割り勘計算
PaymentCalculationService -down-> 請求金額
PaymentCalculationService --> 割り勘計算後金額
PaymentCalculationService --> 飲み会全体の人数
割り勘計算 --> 飲み会全体の人数
割り勘計算 -down-> 請求金額
割り勘計算 --> 割り勘計算後金額
割り勘計算後金額 --> 支払金額
割り勘計算後金額 --> 不足金額
支払金額 --> 多めの人の支払金額
支払金額 --> 普通の人の支払金額
支払金額 --> 少なめの人の支払金額
割り勘計算 --> 多めの人が支払う金額計算
割り勘計算 --> 普通の人が支払う金額計算
割り勘計算 --> 少なめの人が支払う金額計算
割り勘計算 --> 支払金額計算
多めの人が支払う金額計算 -up-> 飲み会全体の人数
多めの人が支払う金額計算 -up-> 請求金額
多めの人が支払う金額計算 --> 多めの人が支払う金額計算結果
多めの人が支払う金額計算結果 --> 多めの人の支払金額
多めの人が支払う金額計算結果 --> 請求額の残額
普通の人が支払う金額計算 -up-> 飲み会全体の人数
普通の人が支払う金額計算 -up-> 請求金額
普通の人が支払う金額計算 --> 多めの人が支払う金額計算結果
普通の人が支払う金額計算 --> 普通の人が支払う金額計算結果
普通の人が支払う金額計算結果 --> 普通の人の支払金額
普通の人が支払う金額計算結果 --> 請求額の残額
少なめの人が支払う金額計算 -up-> 飲み会全体の人数
少なめの人が支払う金額計算 -up-> 請求金額
少なめの人が支払う金額計算 --> 普通の人が支払う金額計算結果
少なめの人が支払う金額計算 --> 少なめの人が支払う金額計算結果
少なめの人が支払う金額計算結果 --> 少なめの人の支払金額
少なめの人が支払う金額計算結果 --> 不足金額
支払金額計算 --> 多めの人が支払う金額計算結果
支払金額計算 --> 普通の人が支払う金額計算結果
支払金額計算 --> 少なめの人が支払う金額計算結果
支払金額計算 --> 割り勘計算後金額
飲み会全体の人数 -down-> 多めの人数
飲み会全体の人数 -down-> 普通の人数
飲み会全体の人数 -down-> 少なめの人数
@enduml